### ISSUE TITLE
Advertising > 1218 characters

### ISSUE THREAD

**Issue by scottlabs** [wankdanker/node-discover#20]
When my service `foo` advertises with a payload greater than 1218 characters (I'm stringifying the object to get the length) it seems that `d.added` doesn't get triggered from other services. Is there some maximum character limit I'm running up against?

**Comment by wankdanker** [comment]
Yeah, you are probably hitting the limit of the UDP payload on your network. This module doesn't handle re-combining messages yet. :( So, if the message ends up getting split into two or more packets then the receiving side will not be able to parse the full message.

**Comment by scottlabs** [comment]
Got it, thanks for the info; this is all happening locally on OS X El Capitan, if that's any help.

For my purposes I can stay under the limit. Thanks for a great library!
