### ISSUE TITLE
Security warning from node-uuid

### ISSUE THREAD

**Issue by laurie71** [wankdanker/node-discover#32]
node-discover is using the deprecated / no-longer-maintained node-uuid module. That is resulting in console.warn messages being logged:

`[SECURITY] node-uuid: crypto not usable, falling back to insecure Math.random()`

I believe the solution is to switch from node-uuid to uuid.

**Comment by wankdanker** [comment]
Thanks for pointing this out. node-discover@1.0.0 has been published to npm.
